### ISSUE TITLE
Bad Results.

### ISSUE THREAD

**Issue by rfww** [cjf8899/CDRL#3]
hello, I augment two widely-used datasets(BCD AICD) with your provided weight and train the CDRL. However, the change map is almost black. Normalization is useless. can you help me? thanks a lot!!!

**Comment by seominseok0429** [comment]
The author doesn't seem to have uploaded the full code.

The author who maintains the code is not in good health, so I'm reorganizing the code and it's taking some time.

**Comment by seominseok0429** [comment]
@rfww can you provide AICD dataset download link? The code will be modified to support up to AICD dataset.

best,

minseok

**Comment by rfww** [comment]
This is AICD download link:
BaiDu link：https://pan.baidu.com/s/1t9hDkBq6RtGWmDOzzMqABw 
code：k180

**Comment by yyaoshuai** [comment]
> This is AICD download link: BaiDu link：https://pan.baidu.com/s/1t9hDkBq6RtGWmDOzzMqABw code：k180

Hello, can you leave a contact information? I don't understand some parts of this code and would like to ask?

**Comment by rfww** [comment]
> > This is AICD download link: BaiDu link：https://pan.baidu.com/s/1t9hDkBq6RtGWmDOzzMqABw code：k180
> 
> Hello, can you leave a contact information? I don't understand some parts of this code and would like to ask?

We chat : rfeiwang
